#!/bin/bash
#:r !env | grep SSH_
#
export SSH_AGENT_PID SSH_AUTH_SOCK

ncpu=$(grep ^processor /proc/cpuinfo | wc -l)

cd /tmp
rm -rf dalton
git clone --recursive git@gitlab.com:dalton/dalton.git
cd dalton
./setup --mpi -D CPP=-DDISABLE_XC_RESPONSE_SANITY_CHECK
cd build
make -j $ncpu || exit
git clone https://github.com/vahtras/fdrsp.git
cd fdrsp
export PATH=$PATH:/tmp/dalton/build
./submitall all_functionals
#
# scp test_findif.tgz remote_host:
# ssh remote_host tar -C ./pub -xzf test_findif.tgz
