#!/bin/bash
#:r !env | grep SSH_
#
export SSH_AGENT_PID SSH_AUTH_SOCK

cd /tmp
rm -rf dalton
git clone git@repo.ctcc.no:dalton.git
cd dalton
./setup --fc=mpif90 --cc=mpicc --cxx=mpiCC -D CPP=-DDISABLE_XC_RESPONSE_SANITY_CHECK
cd build
make dalton.x || exit
git clone https://github.com/vahtras/fdrsp.git
cd fdrsp
export PATH=$PATH:/tmp/dalton/build
./submitall pure_functionals
#
#tar -C /var/www/dalton -xzf test_findif.tgz
scp test_findif.tgz vidar.biotech.kth.se:
ssh vidar.biotech.kth.se tar -C ./pub -xzf test_findif.tgz
